### ISSUE TITLE
Buildout bootstrap fails! (affects multiple birdhouse components)

### ISSUE THREAD

**Issue by Kruecke** [bird-house/malleefowl#10]
Current (and even older) versions of malleefowl and phoenix are no longer going to be build successfully!

See e.g. https://travis-ci.org/bird-house/pyramid-phoenix/builds/69434202:
```
Bootstrap buildout ...
discarding /home/travis/anaconda/bin from PATH
prepending /home/travis/.conda/envs/birdhouse/bin to PATH
bootstrap.py version 2015-07-01
Installing application with buildout ...
bash -c "source /home/travis/anaconda/bin/activate birdhouse;bin/buildout -c custom.cfg"
discarding /home/travis/anaconda/bin from PATH
prepending /home/travis/.conda/envs/birdhouse/bin to PATH
bash: bin/buildout: No such file or directory
make: *** [install] Error 127
```

The problem here is that a call to `curl` in [bootstrap-buildout.py](https://bootstrap.pypa.io/bootstrap-buildout.py) fails with code 77 ([CURLE_SSL_CACERT_BADFILE](http://curl.haxx.se/libcurl/c/libcurl-errors.html)). A problem *could* be, that old certs that may come with this installation have been expired already. In Makefile this script is called with `--setuptools-version 14.3 --version 2.3.1`. If you omit these parameters, buildout will work again, but the the installation will fail at a later point:
```
Installing application with buildout ...
bash -c "source /home/kruecke/anaconda/bin/activate birdhouse;bin/buildout -c custom.cfg"
discarding /home/kruecke/anaconda/bin from PATH
prepending /home/kruecke/.conda/envs/birdhouse/bin to PATH
Getting distribution for 'buildout.locallib'.
Got buildout.locallib 0.3.1.
Develop: '/home/kruecke/Repositories/malleefowl/.'
warning: no previously-included files matching '*.pyc' found anywhere in distribution
warning: no previously-included files matching '*.*~' found anywhere in distribution
Getting distribution for 'birdhousebuilder.recipe.docker==0.2.1'.
warning: no previously-included files matching '*.pyc' found anywhere in distribution
Got birdhousebuilder.recipe.docker 0.2.1.
Getting distribution for 'birdhousebuilder.recipe.conda==0.2.2'.
warning: no previously-included files matching '*.pyc' found anywhere in distribution
Got birdhousebuilder.recipe.conda 0.2.2.
Getting distribution for 'zc.recipe.egg>=2.0.0a3'.
Got zc.recipe.egg 2.0.2.
Getting distribution for 'birdhousebuilder.recipe.pywps==0.2.6'.
warning: no previously-included files matching '*.pyc' found anywhere in distribution
Got birdhousebuilder.recipe.pywps 0.2.6.
Getting distribution for 'birdhousebuilder.recipe.nginx==0.2.2'.
warning: no previously-included files matching '*.pyc' found anywhere in distribution
Got birdhousebuilder.recipe.nginx 0.2.2.
While:
  Installing.
  Getting section malleefowl_wps.
  Initializing section malleefowl_wps.
  Installing recipe birdhousebuilder.recipe.pywps.
  Getting distribution for 'birdhousebuilder.recipe.supervisor==0.2.2'.

An internal error occurred due to a bug in either zc.buildout or in a
recipe being used:
Traceback (most recent call last):
  File "/home/kruecke/Repositories/malleefowl/eggs/zc.buildout-2.4.0-py2.7.egg/zc/buildout/buildout.py", line 1987, in main
    getattr(buildout, command)(args)
  File "/home/kruecke/Repositories/malleefowl/eggs/zc.buildout-2.4.0-py2.7.egg/zc/buildout/buildout.py", line 552, in install
    [self[part]['recipe'] for part in install_parts]
  File "/home/kruecke/Repositories/malleefowl/eggs/zc.buildout-2.4.0-py2.7.egg/zc/buildout/buildout.py", line 1137, in __getitem__
    options._initialize()
  File "/home/kruecke/Repositories/malleefowl/eggs/zc.buildout-2.4.0-py2.7.egg/zc/buildout/buildout.py", line 1241, in _initialize
    self.initialize()
  File "/home/kruecke/Repositories/malleefowl/eggs/zc.buildout-2.4.0-py2.7.egg/zc/buildout/buildout.py", line 1247, in initialize
    recipe_class = _install_and_load(reqs, 'zc.buildout', entry, buildout)
  File "/home/kruecke/Repositories/malleefowl/eggs/zc.buildout-2.4.0-py2.7.egg/zc/buildout/buildout.py", line 1201, in _install_and_load
    allow_hosts=buildout._allow_hosts
  File "/home/kruecke/Repositories/malleefowl/eggs/zc.buildout-2.4.0-py2.7.egg/zc/buildout/easy_install.py", line 848, in install
    return installer.install(specs, working_set)
  File "/home/kruecke/Repositories/malleefowl/eggs/zc.buildout-2.4.0-py2.7.egg/zc/buildout/easy_install.py", line 685, in install
    for_buildout_run=for_buildout_run):
  File "/home/kruecke/Repositories/malleefowl/eggs/zc.buildout-2.4.0-py2.7.egg/zc/buildout/easy_install.py", line 477, in _get_dist
    dist, avail = self._satisfied(requirement)
  File "/home/kruecke/Repositories/malleefowl/eggs/zc.buildout-2.4.0-py2.7.egg/zc/buildout/easy_install.py", line 234, in _satisfied
    return None, self._obtain(req, source)
  File "/home/kruecke/Repositories/malleefowl/eggs/zc.buildout-2.4.0-py2.7.egg/zc/buildout/easy_install.py", line 402, in _obtain
    if index.obtain(requirement) is None:
  File "build/bdist.linux-x86_64/egg/setuptools/package_index.py", line 443, in obtain
    self.find_packages(requirement)
  File "build/bdist.linux-x86_64/egg/setuptools/package_index.py", line 427, in find_packages
    self.scan_url(self.index_url + requirement.unsafe_name+'/')
  File "build/bdist.linux-x86_64/egg/setuptools/package_index.py", line 761, in scan_url
    self.process_url(url, True)
  File "build/bdist.linux-x86_64/egg/setuptools/package_index.py", line 304, in process_url
    f = self.open_url(url, "Download error on %s: %%s -- Some packages may not be found!" % url)
  File "build/bdist.linux-x86_64/egg/setuptools/package_index.py", line 700, in open_url
    return open_with_auth(url, self.opener)
  File "build/bdist.linux-x86_64/egg/setuptools/package_index.py", line 894, in _socket_timeout
    return func(*args, **kwargs)
  File "build/bdist.linux-x86_64/egg/setuptools/package_index.py", line 1007, in open_with_auth
    fp = opener(request)
  File "/home/kruecke/.conda/envs/birdhouse/lib/python2.7/urllib2.py", line 431, in open
    response = self._open(req, data)
  File "/home/kruecke/.conda/envs/birdhouse/lib/python2.7/urllib2.py", line 449, in _open
    '_open', req)
  File "/home/kruecke/.conda/envs/birdhouse/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/home/kruecke/.conda/envs/birdhouse/lib/python2.7/urllib2.py", line 1227, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "/home/kruecke/.conda/envs/birdhouse/lib/python2.7/urllib2.py", line 1200, in do_open
    r = h.getresponse(buffering=True)
  File "/home/kruecke/.conda/envs/birdhouse/lib/python2.7/httplib.py", line 1132, in getresponse
    response.begin()
  File "/home/kruecke/.conda/envs/birdhouse/lib/python2.7/httplib.py", line 453, in begin
    version, status, reason = self._read_status()
  File "/home/kruecke/.conda/envs/birdhouse/lib/python2.7/httplib.py", line 409, in _read_status
    line = self.fp.readline(_MAXLINE + 1)
  File "/home/kruecke/.conda/envs/birdhouse/lib/python2.7/socket.py", line 480, in readline
    data = self._sock.recv(self._rbufsize)
error: [Errno 104] Connection reset by peer
make: *** [install] Error 1
```

~~`supervisor==0.2.2` doesn't seem to be available in `malleefowl_wps`. Maybe an upgrade to a newer version of supervisor is required here?~~ I don't really know what that means. Is there no package of supervisor available? Is there a reason why every package version is strictly set?

**Comment by Kruecke** [comment]
Okay, a fix (or at least a workaround) is to omit just the `--version 2.3.1` argument. I wonder what it is for anyway, because this doesn't look like a legal argument when I take a look at `bootstrap-buildout.py`:
```
parser.add_option("--version",
                  action="store_true", default=False,
                  help=("Return bootstrap.py version."))
```

As it seems to affect all birdhouse components, do we have to change the Makefile in every project? Or is this approach wrong in the first place?

**Comment by cehbrecht** [comment]
`buildout/bootstrap.py` was updated some days ago ... they changed the parameters ;)

I have fixed it in the `Makefile` in `birdhousebuilder.bootstrap`. This `Makefile` is used by all birdhouse components. When you run `make selfupdate`  in your "bird" you get the latest version of `Makefile` from birdhousebuilder.boostrap. 

http://birdhousebuilderbootstrap.readthedocs.org/en/latest/index.html

I've already updated the birdhouse components.

**Comment by Kruecke** [comment]
I also recognized that you've changed the version numbers. Where do you get these numbers from? Have you just tested if it works or are the some dependencies to watch out for? Is it necessary to pin-point the version numbers? Or is it just 'good style' for some reason? (So many questions...)

**Comment by cehbrecht** [comment]
there is a Problem with boostrapping setuptools:

https://github.com/bird-house/birdhousebuilder.bootstrap/issues/13

That is why i pin the setuptools to the version in conda ... it's just a workaround ...

I pinned also the buildout version ... just in case.

But i didn't pin the `bootstrap-buildout.py` script ... this is the latest version fetched from 

https://bootstrap.pypa.io/bootstrap-buildout.py

That's why the build was broken ...

The boostrapping needs to fixed/cleaned up ... currently i would prefer to use always the latest versions if possible ...

**Comment by Kruecke** [comment]
Okay. Since the remaining problems are gathered in bird-house/birdhousebuilder.bootstrap#13, I consider this issue being closed.
