### ISSUE TITLE
fx time aggregation does not with with malleefowl esgf.search

### ISSUE THREAD

**Issue by cehbrecht** [bird-house/malleefowl#21]
A fetch process for 'fx' time aggregation (Orography) failed.

here is the log of malleefowl:

PyWPS [2016-03-24 13:26:27,161] INFO: Execution status=ProcessStarted
PyWPS [2016-03-24 13:26:27,161] INFO: Percent completed=0
PyWPS [2016-03-24 13:26:27,161] INFO: Status message=Process esgsearch started
PyWPS [2016-03-24 13:26:27,162] INFO: Sleeping 3 seconds...
PyWPS [2016-03-24 13:26:27,371] ERROR: Search job failed! Could not retrieve files/aggregations.
Traceback (most recent call last):
  File "/homel/birdhouse/malleefowl/malleefowl/esgf/search.py", line 245, in threader
    self._file_search_job(**worker)
  File "/homel/birdhouse/malleefowl/malleefowl/esgf/search.py", line 255, in _file_search_job
    if not temporal_filter(f.filename, start_date, end_date):
  File "/homel/birdhouse/malleefowl/malleefowl/esgf/search.py", line 60, in temporal_filter
    start_year, end_year = date_from_filename(filename)
  File "/homel/birdhouse/malleefowl/malleefowl/esgf/search.py", line 21, in date_from_filename
    start_year = int(value[0][:4]) # keep only the year
ValueError: invalid literal for int() with base 10: 'fx'

**Comment by cehbrecht** [comment]
done.
