### ISSUE TITLE
download process failed with latest pywps

### ISSUE THREAD

**Issue by cehbrecht** [bird-house/malleefowl#30]
downloading several cmip5 files. Got exception:

```
2017-05-30 15:49:21,515] [ERROR] line=153 module=download download failed!
Traceback (most recent call last):
  File "/home/Shared/pingu/sandbox/birdhouse/malleefowl/malleefowl/download.py", line 149, in threader
    self.download_job(**worker)
  File "/home/Shared/pingu/sandbox/birdhouse/malleefowl/malleefowl/download.py", line 166, in download_job
    progress)
  File "/home/Shared/pingu/sandbox/birdhouse/malleefowl/malleefowl/download.py", line 138, in show_status
    self.monitor(message, progress)
  File "/home/Shared/pingu/sandbox/birdhouse/malleefowl/malleefowl/processes/wps_download.py", line 65, in monitor
    response.update_status(msg, progress)
  File "/home/pingu/.conda/envs/malleefowl/lib/python2.7/site-packages/pywps/app/WPSResponse.py", line 75, in update_status
    update_response(self.uuid, self)
  File "/home/pingu/.conda/envs/malleefowl/lib/python2.7/site-packages/pywps/dblog.py", line 138, in update_response
    if requests.count():
  File "/home/pingu/.conda/envs/malleefowl/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 3089, in count
    return self.from_self(col).scalar()
  File "/home/pingu/.conda/envs/malleefowl/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2843, in scalar
    ret = self.one()
  File "/home/pingu/.conda/envs/malleefowl/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2814, in one
    ret = self.one_or_none()
  File "/home/pingu/.conda/envs/malleefowl/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2784, in one_or_none
    ret = list(self)
  File "/home/pingu/.conda/envs/malleefowl/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2855, in __iter__
    return self._execute_and_instances(context)
  File "/home/pingu/.conda/envs/malleefowl/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2878, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "/home/pingu/.conda/envs/malleefowl/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 945, in execute
    return meth(self, multiparams, params)
  File "/home/pingu/.conda/envs/malleefowl/lib/python2.7/site-packages/sqlalchemy/sql/elements.py", line 263, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/home/pingu/.conda/envs/malleefowl/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1053, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/home/pingu/.conda/envs/malleefowl/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1189, in _execute_context
    context)
  File "/home/pingu/.conda/envs/malleefowl/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1402, in _handle_dbapi_exception
    exc_info
  File "/home/pingu/.conda/envs/malleefowl/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 203, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/home/pingu/.conda/envs/malleefowl/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1182, in _execute_context
    context)
  File "/home/pingu/.conda/envs/malleefowl/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 470, in do_execute
    cursor.execute(statement, parameters)
OperationalError: (sqlite3.OperationalError) no such table: pywps_requests [SQL: u'SELECT count(*) AS count_1 \nFROM (SELECT pywps_requests.uuid AS pywps_requests_uuid, pywps_requests.pid AS pywps_requests_pid, pywps_requests.operation AS pywps_requests_operation, pywps_requests.version AS pywps_requests_version, pywps_requests.time_start AS pywps_requests_time_start, pywps_requests.time_end AS pywps_requests_time_end, pywps_requests.identifier AS pywps_requests_identifier, pywps_requests.message AS pywps_requests_message, pywps_requests.percent_done AS pywps_requests_percent_done, pywps_requests.status AS pywps_requests_status \nFROM pywps_requests \nWHERE pywps_requests.uuid = ?) AS anon_1'] [parameters: ('c89dd80e-453e-11e7-8502-68f72837e1b4',)]
```

**Comment by cehbrecht** [comment]
out-dated.
