### ISSUE TITLE
Installation fails on ubuntu 18 (any bird)

### ISSUE THREAD

**Issue by nkadygrov** [bird-house/malleefowl#33]
## Way to reproduce:
```
"/home/sthao/anaconda/bin/conda" install -y -n malleefowl setuptools=36.5.0
Solving environment: done


==> WARNING: A newer version of conda exists. <==
  current version: 4.4.11
  latest version: 4.5.5

Please update conda by running

    $ conda update -n base conda



## Package Plan ##

  environment location: /home/sthao/.conda/envs/malleefowl

  added / updated specs:
    - setuptools=36.5.0


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    certifi-2018.4.16          |           py27_0         142 KB

The following packages will be UPDATED:

    certifi:         2018.4.16-py27_0 conda-forge --> 2018.4.16-py27_0
    openssl:         1.0.2o-0         conda-forge --> 1.0.2o-h20670df_0

The following packages will be DOWNGRADED:

    ca-certificates: 2018.4.16-0      conda-forge --> 2018.03.07-0    


Downloading and Extracting Packages
certifi 2018.4.16: ################################################################################################################################################################################# | 100%
Preparing transaction: done
Verifying transaction: done
Executing transaction: done
Update pinned conda packages ...
Update buildout bootstrap-buildout.py ...
Bootstrap buildout ...
ez_setup.py is deprecated and when using it setuptools will be pinned to 33.1.1 since it's the last version that supports setuptools self upgrade/installation, check https://github.com/pypa/setuptools/issues/581 for more info; use pip to install setuptools
Traceback (most recent call last):
  File "bootstrap-buildout.py", line 200, in <module>
    import zc.buildout.buildout
  File "/tmp/bootstrap-bGD7T9/zc.buildout-2.10.0-py2.7.egg/zc/buildout/buildout.py", line 18, in <module>
    import zc.buildout.easy_install
  File "/tmp/bootstrap-bGD7T9/zc.buildout-2.10.0-py2.7.egg/zc/buildout/easy_install.py", line 45, in <module>
    pkg_resources.SetuptoolsVersion(setuptools_version) >=
AttributeError: 'module' object has no attribute 'SetuptoolsVersion'
Makefile:184: recipe for target 'bootstrap' failed
make: *** [bootstrap] Error 1
```
May be related to: https://github.com/buildout/buildout/issues/442
But works fine on ubuntu16 but not with ubuntu18...

**Comment by nkadygrov** [comment]
Solved for malleefowl on ubuntu18 by changing buildout version to 2.11.2
in ~/birdhouse/malleefowl/Makefile
change version of buildout to 2.11.2:
BUILDOUT_VERSION := 2.11.2

**Comment by cehbrecht** [comment]
@nkadygrov I have updated master to latest buildout 2.12.1. It works for me on Ubuntu 18. Please complain if there is still an issue.
